name: Bump

on: 
  schedule:
    - cron: 0 11 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Deno
      run: |
        denov=$(cat .denov)
        curl -fsSL https://deno.land/x/install/install.sh | bash -s -- ${denov}
    - name: Check And Bump
      run: |
        export PATH=$HOME/.deno/bin:$PATH
        GITHUB_USER=keroxp GITHUB_REPO=dink-bot deno -A main.ts
